id = "v0-theme-lighter-zed"
name = "v0 theme-lighter-zed"
version = "0.5.76"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "Theme used in v0 chat ported for zed"
repository = "https://github.com/biaqat/v0-theme-zed"
